# Makefile for the DSM Audio drivers.
#
# Each configuration option enables a list of files.
ccflags-y += -Idrivers/devkit/audiokit/dsm_audio
dsm-audio-objs :=dsm_audio.o
obj-$(CONFIG_HUAWEI_DSM_AUDIO)  += dsm-audio.o
